### PR TITLE
Add solution-path option

### PR DESCRIPTION
**Pull request by Methuselah96**

### CODE REVIEW

**Comment by Methuselah96** [comment]
Updated the built files.

**Comment by Methuselah96** [comment]
Hmmm..., maybe line endings differ?

**Comment by Methuselah96** [comment]
But the diff is run using `--ignore-space-at-eol`. 😕

**Comment by Methuselah96** [comment]
Oh, nice it uploads the built dist in CI as an artifact. Taking a look.

**Comment by leonardochaia** [comment]
Hi @Methuselah96 sorry  I haven't been able to spend more time on this.
Will get merged once it builds :+1: 

Thanks!
Leo.

**Comment by Methuselah96** [comment]
No problem, thanks for merging, I might send a few more issues and pull requests as I have time. I really appreciate your effort on `dotnet-affected`, it was just what I was needing.

**Comment by leonardochaia** [comment]
Hi @Methuselah96 , thank you, it's great to know you are using dotnet-affected.
Feel free to send PR/issues and I'll take a look as soon as I can :+1: 

Leo.

**Pull request merged**
