### PR TITLE
Add exclude argument

### PR DESCRIPTION
**Pull request by Methuselah96**

### CODE REVIEW

**Comment by leonardochaia** [comment]
Hi Nathan! thanks for the PR! :+1: 
Have a great week!

Regards,
Leo.

**Comment by Methuselah96** [comment]
Thanks, you too! Let me know when you get a chance to release this to the `v1` tag.

**Comment by leonardochaia** [comment]
Hey Nathan, [v1.3](https://github.com/leonardochaia/dotnet-affected-action/releases/tag/v1.3) has been released :+1: 

Cheers,
Leo.

**Comment by Methuselah96** [comment]
Thanks! Do you mind updating the `v1` tag to point to that when you get a chance?

**Pull request merged**
